app:
  name: "RAG System with Qdrant"
  version: "0.1.0"

qdrant:
  host: "qdrant"
  port: 6333
  collection_name: "documents"

embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

llm:
  model: "gpt-4o-mini"
  max_tokens: 1000

document_processing:
  chunk_size: 1000
  chunk_overlap: 200