services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RAG System CLI
  rag-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_cli
    volumes:
      - ./documents:/app/documents
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - rag_network
    profiles:
      - cli

volumes:
  qdrant_data:
    driver: local

networks:
  rag_network: